version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    command: --replSet rs0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: