version: '3.8'
services:
  mongo:
    image: mongo:latest
    restart: always
    container_name: mongodb
    command: --replSet rs0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  express-js-forms-app:
    image: express-js-forms-app
    container_name: express-app
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongo
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    name: app-network